services:
  db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_USER: WalkiniAdmin
        POSTGRES_PASSWORD: password
        PGDATA: /data/walkini
      volumes:
        - db:/data/walkini
      ports:
        - "5332:5432"
      networks:
        - db
      restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db:



